### PR TITLE
Address typo in  logging.md

### PR DESCRIPTION
**Pull request by kamalogudah**
Address Typo in the documentation.

### CODE REVIEW

**Comment by adam12** [comment]
Did you want to tackle the grammar error in that same line while you're here?

> and then just tell<strike>ing</strike> logger to use our new formatter for logging

**Comment by kamalogudah** [comment]
> Did you want to tackle the grammar error in that same line while you're here?
> 
> > and then just telling logger to use our new formatter for logging

sure

**Review by adam12 — APPROVED** [review]

**Comment by adam12** [comment]
:+1: LGTM! cc @jodosha

**Comment by adam12** [comment]
Thanks for the patch!

**Pull request merged**
