### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by poudelmadhav**
homes is renamed to home

### CODE REVIEW

**Comment by davydovanton** [comment]
hey, I have a question. Are you sure that we need to use `home` for controller name instead `homes`? @hanami/core WDYT?

**Comment by poudelmadhav** [comment]
As you have previously created the controller name `home`, but at this line you have used `homes`. So I have suggesting you.

**Comment by davydovanton** [comment]
Got it! Good catch 👏

**Comment by poudelmadhav** [comment]
Welcome

**Pull request merged**
